Added the aws credentials to github
aodn/ogcapi-java pull request #14
Opened 2023-11-16 00:25 UTC by nandeeshsb9

2023-12-05 05:38 UTC, vietnguyengit requested changes
same here, please tidy up the commits history, thank you

2023-12-05 22:48 UTC, utas-raymondng requested changes

2023-12-05 22:48 UTC, utas-raymondng commented on ogcapi-java-dev-td.json
> +{
Is there way to integrate docker-compose.yml together, cost dev need to maintain two very similar config one for docker one for aws tasks

2023-12-06 01:42 UTC, priyaranjanpatil commented on .github/workflows/github-actions.yml
> +    branches: [5165-cicd]
After testing the deployment will have to point to main branch only for PR and push

2023-12-07 01:40 UTC, closed without merging

2023-12-07 01:40 UTC, priyaranjanpatil commented
Closing this PR and will create a new one after rebase and squash with few env var config changes